services:
  fxterminal-tcp-v1:
    image: nmhung1210/repo:fxterminal-tcp-v1
    restart: always
    ports:
      - "8888:8888"
  fxterminal-tcp-v2:
    image: nmhung1210/repo:fxterminal-tcp-v2
    restart: always
    ports:
      - "8899:8888"
      
